openapi: "3.0.1"
info:
  title: "Tzvi Schamovic Resume"
  description: "Get Resume info"
  version: "1.0.0"
  contact: 
    name: TzviSchamovic API
    email: "tschams2@gmail.com"
servers:
  - url: http://api.tzvi-schamovic
    description: Production server
paths:
  /technical-skills:
    get:
      tags:
      - Technical Skills
      summary: "Returns my technical skills"
      operationId: "getSkills"
      responses:
        200:
          description: successful operation
          content:
            application/json: 
              schema:
                type: object
                properties:
                  data:
                    type: array      
                    items:
                      type: object    
                      properties:        
                        type:
                          type: string 
                        id:
                          type: string 
                        attributes:
                          type: object 
                          properties: 
                            name:
                              type: string
        404:
          description: Not Found Response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/errors'
        405:
          description: Method Not Allowed Response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/errors'
        default:
          description: Unexpected error
  /institutions:
    get:
      tags:
      - Institutions
      summary: "Returns my institutions"
      operationId: "getInstitutions"
      responses:
        200:
          description: successful operation
          content:
            application/json: 
              schema:
                type: object
                properties:
                  data:
                    type: array      
                    items:
                      type: object    
                      properties:        
                        type:
                          type: string 
                        id:
                          type: string 
                        attributes:
                          type: object 
                          properties: 
                            title:
                              type: string
                            organization:
                              type: string
        404:
          description: Not found response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/errors'
        405:
          description: Method Not Allowed Response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/errors'
        default:
          description: Unexpected error
  /institutions/{id}:
    get:
      tags:
      - Institution Info
      summary: "Returns my institution info"
      operationId: "getInstitutionInfo"
      parameters:
        - name: id
          in: path
          description: "id of institution"
          schema:
            type: string
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json: 
              schema:
                type: object
                properties:
                  data:
                    type: array      
                    items:
                      type: object    
                      properties:        
                        type:
                          type: string 
                        id:
                          type: string 
                        attributes:
                          type: object 
                          properties: 
                            title:
                              type: string
                            organization:
                              type: string
                            start_date:
                              type: string
                            end-date:
                              type: string
                            location:
                              type: string
        404:
          description: Not found response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/errors'
        405:
          description: Method Not Allowed Response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/errors'
        default:
          description: Unexpected error
components:
  schemas:
    errors:
      type: object
      properties:
        errors:
          type: array      
          items:
            type: object    
            properties:
              status:
                type: string
              source: 
                type: object
                properties:
                  pointer:
                    type: string
              detail:
                type: string